scadinspect: resources/ ../target/SCADinspect-1.0.jar
	rm -rf SCADinspect.app
	mkdir SCADinspect.app
	cp -r resources/Contents SCADinspect.app/.
	cp ../target/SCADinspect-1.0.jar SCADinspect.app/Contents/Java/SCADinspect.jar

